name: CI

on:
  push:
    branches-ignore:
      - "**/docs?"
  pull_request:
    branches-ignore:
      - "**/docs?"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]

    steps:
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          ./.github/scripts/install-build-deps.sh
          ./.github/scripts/setup-github-hosted.sh
      - name: Configure myself
        run: cmake -S . -B build
      - name: Cache llvm-src
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-src
          key: ${{ matrix.os }}-llvm-src-202108-1
      - name: Cache llvm-build
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-build
          key: ${{ matrix.os }}-llvm-build-202108-1
      - name: Cache llvm-subbuild
        uses: actions/cache@v1
        with:
          path: build/_deps/llvm-subbuild
          key: ${{ matrix.os }}-llvm-subbuild-202108-1
      - name: Build myself
        run: cmake --build build --target all
      - name: Test myself
        run: cmake --build build --target test

  cosim:
    if: github.event_name == 'push' && github.repository == 'UCLA-VAST/tapa'

    runs-on:
      - self-hosted
      - Linux
      - xilinx-tools

    strategy:
      matrix:
        xocl-version:
          - 2020.2
          - 2021.1
          - 2021.2

    env:
      XILINX_HLS: /opt/tools/xilinx/Vitis_HLS/${{ matrix.xocl-version }}
      XILINX_VITIS: /opt/tools/xilinx/Vitis/${{ matrix.xocl-version }}
      XILINX_VIVADO: /opt/tools/xilinx/Vivado/${{ matrix.xocl-version }}

    steps:
      - name: Checkout myself
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          .github/scripts/install-build-deps.sh
          .github/scripts/setup-self-hosted.sh
          python3 -m pip install --upgrade build
          python3 -m build backend/python
          python3 -m pip install backend/python/dist/*.whl

          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            xilinx-u250-xdma-dev \
            xilinx-u280-xdma-dev \

      - name: Configure myself
        run: cmake -S . -B build
      - name: Build myself
        run: cmake --build build --target all --parallel $(nproc)
      - name: Test myself
        working-directory: build
        run: |
          source ${XILINX_VITIS}/settings64.sh
          /usr/local/bin/ctest --verbose --parallel $(nproc)
